### ISSUE TITLE
Import/Export Config Command

### ISSUE THREAD

**Issue by bergren2** [rehret/marco#5]
Would be cool to have this available rather than hunting through directories.

**Comment by rehret** [comment]
What's the desired output here? Should it dump the json to stdout? Prompt for a file location to write to?

**Comment by bergren2** [comment]
I think prompting for file input/output makes sense.

**Comment by rehret** [comment]
The more I think about this, the more I think we might want to go with the stdout approach. It would let the user do things like `marco export | xclip` to allow for easy sharing. You could also do `marco export > ~/marco.backup.json` (assuming bash).
